---
version: "2"
services:
  database:
    image: postgres
    container_name: chess-data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
