---
version: "2"
services:
  database:
    image: postgres
    container_name: chess-data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  database-dev:
    image: postgres
    container_name: chess-data-dev
    volumes:
      - ./test-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
